export const restaurantQueries = {
  selectRestaurant: `Restaurant.id as id, 
    Restaurant.name as name,
    Restaurant.description as description,
    Restaurant.type as type,
    Restaurant.cuisines as cuisines,
    Restaurant.ambience as ambience ,
    Restaurant.seatingType as seatingType,
    Restaurant.imageUrl as imageUrl,
    Restaurant.hasSmokingArea as hasSmokingArea,
    Restaurant.address as address,
    Restaurant.country as country ,
    Restaurant.state as state ,
    Restaurant.city as city,
    Restaurant.zipCode as zipCode ,
    Restaurant.longitudes as longitudes ,
    Restaurant.latitudes as latitudes ,
    Restaurant.isDeleted as isDeleted ,
    Restaurant.isApproved as isApproved ,
    Restaurant.createdDate as createdDate ,
    Restaurant.createdBy as createdBy ,
    Restaurant.updatedDate as updatedDate ,
    Restaurant.updatedBy as updatedBy ,
    RestaurantOperatingHour.OpenTime as openTime, 
    RestaurantOperatingHour.ClosingTime as closingTime,  
    RestaurantOperatingHour.Day as Day`,
};
