import "reflect-metadata";
import { createConnection } from "typeorm";
import * as express from "express";
import * as bodyParser from "body-parser";
import * as helmet from "helmet";
import * as cors from "cors";
import routes from "./routes";
import * as swaggerUi from "swagger-ui-express";

//Connects to the Database -> then starts the express
createConnection()
  .then(async connection => {
    // Create a new express application instance
    const app = express();

    // Call midlewares
    app.use(cors());
    app.use(helmet());
    app.use(bodyParser.json());
    const swaggerJsdoc = require('swagger-jsdoc');

    const options = {
      swaggerDefinition: {
        info: {
          title: 'Test API',
          version: '1.0.0',
          description: 'Test Express API with autogenerated swagger doc',
        },
      },
      apis: ['./routes/**/*.js'],
    };

    const specs = swaggerJsdoc(options);

    

    app.use('/swagger', swaggerUi.serve, swaggerUi.setup(specs));
  
    //Set all routes from routes folder
    app.use("/", routes);

    app.listen(process.env.PORT || 3000, () => {
      console.log("Server started on port 3000!");
    });
  })
  .catch(error => console.log(error));