import * as bodyParser from 'body-parser';
import * as cors from 'cors';
import * as express from 'express';
import * as helmet from 'helmet';
import 'reflect-metadata';
import * as swaggerUi from 'swagger-ui-express';
import { createConnection } from 'typeorm';
import routes from './routes';

// Connects to the Database -> then starts the express
createConnection()
  .then(async connection => {
    // Create a new express application instance
    const app = express();

    // Call midlewares
    app.use(cors());
    app.use(helmet());
    app.use(bodyParser.json());
    const swaggerJsdoc = require('swagger-jsdoc');

    const options = {
      apis: ['./routes/**/*.js'],
      swaggerDefinition: {
        info: {
          description: 'Test Express API with autogenerated swagger doc',
          title: 'Test API',
          version: '1.0.0',
        },
      },
    };

    const specs = swaggerJsdoc(options);

    app.use('/swagger', swaggerUi.serve, swaggerUi.setup(specs));
    // Set all routes from routes folder
    app.use('/', routes);

    app.listen(process.env.PORT || 3000, () => {
      console.log('Server started on port 3000!');
    });
  })
  .catch(error => console.log(error));
